// Scheduled market-narrative agent.
//
// Reads data/inventory.json, asks Claude to web-search current resale
// conditions for each active SELL event, and writes a dated market brief to
// data/briefs/YYYY-MM-DD.md. The GitHub Actions workflow commits the result,
// which triggers a Vercel redeploy so the brief reaches every device.
//
// This produces market *narrative* (directional signals, demand context) —
// not exact live section floors, which aren't reliably scrapeable.
//
// Run from the repo root:  node scripts/market-brief.mjs
// Requires env: ANTHROPIC_API_KEY. Optional: MODEL (default claude-opus-4-8).

import Anthropic from "@anthropic-ai/sdk";
import { readFile, mkdir, writeFile } from "fs/promises";
import path from "path";
import { activeSellEvents, generateBrief, extractBriefNotes } from "./lib/brief-core.mjs";

const ROOT = process.cwd();
const MODEL = process.env.MODEL || "claude-opus-4-8";

async function main() {
  if (!process.env.ANTHROPIC_API_KEY) {
    throw new Error("ANTHROPIC_API_KEY is not set.");
  }

  const inv = JSON.parse(await readFile(path.join(ROOT, "data", "inventory.json"), "utf-8"));
  const events = activeSellEvents(inv.positions);

  const today = new Date().toISOString().slice(0, 10);
  const briefsDir = path.join(ROOT, "data", "briefs");
  await mkdir(briefsDir, { recursive: true });
  const outPath = path.join(briefsDir, `${today}.md`);

  const notesPath = path.join(ROOT, "data", "brief-notes.json");

  if (events.length === 0) {
    const body = `# Market Brief — ${today}\n\nNo active SELL positions to analyze.\n`;
    await writeFile(outPath, body);
    await writeFile(notesPath, JSON.stringify({ generatedAt: today, notes: {} }, null, 2) + "\n");
    console.log(`No active SELL positions. Wrote placeholder to ${outPath}`);
    return;
  }

  const client = new Anthropic({ timeout: 9 * 60 * 1000 });
  console.log(`Generating brief for ${events.length} event(s) with ${MODEL}…`);
  const brief = await generateBrief(client, events, MODEL);

  const body = `# Market Brief — ${today}\n\n_Generated by the scheduled market agent (${MODEL}). Directional read, not exact live section floors._\n\n${brief}\n`;
  await writeFile(outPath, body);
  console.log(`Wrote ${outPath}`);

  // Second pass: distill a one-line snippet per position for the dashboard's
  // Inventory rows. Written to a separate file (never inventory.json), so it
  // can't conflict with dashboard edits. Failure here doesn't lose the brief.
  const positions = events.flatMap((e) => e.positions);
  let notes = {};
  try {
    notes = await extractBriefNotes(client, brief, positions, MODEL);
    console.log(`Extracted ${Object.keys(notes).length} per-position snippet(s).`);
  } catch (err) {
    console.error(`Brief-notes extraction failed (brief still saved): ${err.message || err}`);
  }
  await writeFile(notesPath, JSON.stringify({ generatedAt: today, notes }, null, 2) + "\n");
  console.log(`Wrote ${notesPath}`);
}

main().catch((err) => {
  console.error(err.message || err);
  process.exit(1);
});
